### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by Icecrustly** [GAVC-Website/EI-Website#2]
- That Bright green is supposed to be there, but is a placeholder for the slideshow. 
- Sometimes the header exists other times it doesn't. Right now it doesn't
- All of the navigation are dead links, but we're pretending that's intentional and not me being dumb

**Comment by Shadow-Diamond** [comment]
The header part confuses me, but the rest seems fine

**Comment by Shadow-Diamond** [comment]
This issue will never be fixed
